# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Import and path setup ---------------------------------------------------

import os
import sys

import sphinx_gallery.gen_rst  # type: ignore
from sphinx_gallery.sorting import FileNameSortKey  # type: ignore

import pyresiflex

sys.path.insert(0, os.path.abspath("../"))


# -- Project information ------------------------------------------------------

project = "pyresiflex"
copyright = "GNU GPLv3"
author = "Pierre-Antoine Goutier"
version = pyresiflex.__version__
release = pyresiflex.__version__


# -- General configuration ----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    # Official Sphinx extensions.
    "sphinx.ext.autodoc",  # Core library for html generation from docstrings.
    "sphinx.ext.autosummary",  # Create neat summary tables.
    "sphinx.ext.intersphinx",  # Link to other project's documentation.
    "sphinx.ext.mathjax",  # Render math via LaTeX.
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings.
    # Third-party extensions.
    "autoapi.extension",  # Generate API documentation from docstrings.
    "myst_parser",  # To parse markdown files.
    "sphinx_gallery.gen_gallery",  # Generate an examples gallery.
]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- autodoc configuration ----------------------------------------------------

# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autoclass_content
autoclass_content = "both"
# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings
autodoc_inherit_docstrings = False


# -- Intersphinx configuration ------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
}


# -- Napoleon configuration ---------------------------------------------------

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_preprocess_types = True

napoleon_use_param = True
napoleon_type_aliases = {
    # Cable
    "PerfectCable": "~pyresiflex.cable.cable.PerfectCable",  # noqa: E501
    # Generator
    "BaseGenerator": "~pyresiflex.generator.base_generator.BaseGenerator",  # noqa: E501
    "PurelyResistiveBaseGenerator": "~pyresiflex.generator.base_generator.PurelyResistiveBaseGenerator",  # noqa: E501
    "ComplexImpedanceBaseGenerator": "~pyresiflex.generator.base_generator.ComplexImpedanceBaseGenerator",  # noqa: E501
    # Load
    "BaseLoad": "~pyresiflex.load.base_load.BaseLoad",  # noqa: E501
    "BaseResistance": "~pyresiflex.load.base_load.BaseResistance",  # noqa: E501
    "BaseSteadyImpedance": "~pyresiflex.load.base_load.BaseSteadyImpedance",  # noqa: E501
    # Matplotlib
    "Figure": "matplotlib.figure.Figure",
    "Axes": "matplotlib.axes.Axes",
    # Path
    "Path": "pathlib.Path",
}


# -- AutoAPI configuration ---------------------------------------------------

autoapi_dirs = ["../src/pyresiflex"]
autoapi_ignore = ["*/version.py"]
autoapi_options = [  # https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_options
    "members",
    "inherited-members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
]
autoapi_add_toctree_entry = False
autoapi_root = "_api"
autoapi_keep_files = True


# -- Options for Sphinx Gallery -----------------------------------------------

# https://github.com/sphinx-gallery/sphinx-gallery/issues/978
sphinx_gallery.gen_rst.EXAMPLE_HEADER = """
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "{0}"
.. LINE NUMBERS ARE GIVEN BELOW.

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_{1}:

"""

sphinx_gallery_conf = {
    # Path to your example scripts.
    "examples_dirs": "../examples",
    # Path to where to save gallery generated output.
    "gallery_dirs": "auto_examples",
    # To make references clickable.
    "reference_url": {
        "pyresiflex": None,
    },
    # Directory where function/class granular galleries are stored.
    "backreferences_dir": "source/backreferences",
    # Modules for which function/class level galleries are created.
    # In the case of pyresiflex, this is a tuple of strings:
    "doc_module": ("pyresiflex",),
    "inspect_global_variables": True,
    "show_signature": False,
    # Sort example files within gallery subsections with their filename.
    "within_subsection_order": FileNameSortKey,
    # Animate the example.
    "matplotlib_animations": True,
}

# Used for mini-galleries.
# https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation
autosummary_generate = True

# See https://github.com/sphinx-doc/sphinx/issues/12300
# This is to avoid `WARNING: cannot cache unpickable configuration value`
suppress_warnings = ["config.cache"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = "pydata_sphinx_theme"

html_show_sourcelink = False  # remove 'view source code' from top of page

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_logo = "img/pyresiflex_logo.png"

# Add GitHub link to the navbar.
# See https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#icon-links
html_theme_options = {
    "icon_links": [
        {
            # Label for this link.
            "name": "GitHub",
            # URL where the link will redirect.
            "url": "https://github.com/pag1pag/pyresiflex",  # Required.
            # Icon class (if "type": "fontawesome"),
            # or path to local image (if "type": "local").
            "icon": "fa-brands fa-square-github",
            # The type of image to be used (see below for details).
            "type": "fontawesome",
        }
    ]
}
